#Disable some heads here
#They only will be removed on a database update or a server restart/reload
disabled-heads:
#  - "Chorus Plant"
#  - "ID:7302"
#  - "TAG:Animals"


#Disable categories here
#They only will be removed on a database update or a server restart/reload
disabled-categories:
  - ""
#  - "custom"

# change the names of the heads here
#  ID: "name here"
rename-heads:
  3229: "&oBarrier Block"
#  12105: "Iron Armour Herobrine"
  
# Toggle for showing the info and suggestions buttons in the main inventory
info-enabled: true
suggest-enabled: true
search-enabled: true
featured-tags-enabled: true
main-menu-category-slots: "10,11,12,13,14,15,16,19,20,21,22,23,24,25,28,29,30,31,32,33,34"
main-menu-info-slot: 41
main-menu-suggest-slot: 42
main-menu-search-slot: 43

# Featured tags
main-menu-featured-tags-slots: "37,38,39,40"
# [title]:[id,id...]:[search]:[startMonth-startDay]:[endMonth-endDay]
featured-tags:
  - "&eHalloween:13779,12750,13584,12581:Halloween:10-20:11-7"
  - "&bChristmas:1594,3158,2910:Christmas:11-24:12-31"
  - "&6Happy new year:4446,4447,4448:Firework:1-1:1-7"
  - "&cValentine's Day:14696,14691,14672,14687,14673:Valentine:2-1:2-21"
  - "&cHappy 4th of July:890:Firework:7-3:7-5"
  - "&fEaster:726:Easter:3-20:4-30"

# seasons
  - "&fWinter:3295,1697:Winter:10-25:12-31"
  - "&fWinter:3295,1697:Winter:1-1:3-31"
  
  - "&6Summer:573:summer:6-15:9-30"
  
# fun special days
  - "&3May the 4th be with you:14018,11622,8108,14028:Star wars:5-1:5-8"
  - "&3Pi day:13603,45,57,46:Pie:3-13:3-15"
  - "&6Pokémon Day:13797,8642,1644,2457:Pokemon:2-26:2-28"

# Toggle for using a arrow (only back and next) instead of the paper web based one
# Also moves the back to main menu to the middle and removes the compass
arrow-menu-nav-enabled: false
arrow-menu-search-enabled: true
arrow-menu-current-page-enabled: true
#slots
back-to-menu-slot: 45
arrow-back-slot: 47
current-page-slot: 49
arrow-next-slot: 51
arrow-search-slot: 53

#items (also work on the other paper navigation system)
#all the items have to be different from eachother
arrow-item: "arrow"
paper-page-item: "paper"
current-page-item: "empty_map"
back-to-menu-item: "book"
info-item: "sign"
suggest-item: "writeable_book"
search-item: "compass"
background-item: "stained_glass_pane:8"
background-border-item: "stained_glass_pane:7" 
loading-head-item: "skull_item:3"


# Toggle for chat search, if false it will ask you to do the command instead.
use-chat-search: false

# Close inventory when you don't have enough money to buy a head
close-inventory-on-failed-purchase: false

# Toggle for returning lore and name to the item when picked up
return-name-on-pickup: true

# Experimental async head loading
experimental-loading: true
loadHeadAmount: 9
loadTimeDelay: 10.0

#Change the messages here, you can use & to use colors.
#buyMessage must contain %Item% and %price%
#database can contain "%count%"
messages:
   prefix: "&6HeadDB> "
   database: "&4Head DB&8 %count% heads"
   search: "&4Head Search&8 %count% heads"
   page: "Page"
   price: "&aPrice: &2"
   heads: "heads"
   head: "head"
   other: "other"
   loading: "&c..Loading.."
   recentHeads: "&aRecently added"
   noPermissionToBuyLore: "&cNo Permission"
   searchCommand: "&7/hdb search [input]"
   loreColor: "&8"
   headItemColor: "&9"
   categoryColor: "&c&l"
   categoryLoreColor: "&e"
   
   noPermission: "&cyou are not allowed to do that!"
   notEnoughMoney: "&cYou don't have enough money to do this!"
   notEnoughSpace: "&cYou don't have enough space in your inventory!"
   buyMessage: "&aYou bought %item% &afor &2%price%"
   backToMenu: "&cBack to menu"
   lookingFor: "&eLooking for"
   clickToSearch: "&a&n&lClick here&b to search for heads"
   noHeadsFound: "&eNo heads found, try again!"
   moreSpecific: "&ePlease be more specific!"
   headsFound: "&eHeads found!"
   searchForHeads: "&cSearch for heads"
   pluginInfo: "&cPlugin info"
   pluginSuggest: "&cSuggest Heads"
   chatSearch: "&bType in your search input"
   databaseStillLoading: "&cDatabase is still loading, try again in a second!"

   category-names:
      alphabet: "Alphabet"
      animals: "Animals"
      blocks: "Blocks"
      decoration: "Decoration"
      food_drinks: "Food and Drinks"
      humans: "Humans"
      humanoid: "Humanoid"
      miscellaneous: "Miscellaneous"
      monsters: "Monsters"
      plants: "Plants"
      custom: "Helpers"
      custom2: "Modertors"
      custom3: "Admins"
      custom4: "Owners"
      online_players: "Online Players"


#Enable Economy here
#If the price is 0 it won't show up!
Economy-Enabled: true
Economy-Currency: "$"
#Type can be "item", "currency" or "playerpoints"
Economy-Type: currency
Economy-Item: gold_ingot
#if ItemName equals "" then it accepts the item without any name
Economy-ItemName: ""

alphabet-price: 2000
animals-price: 2000
blocks-price: 2000
decoration-price: 2000
food_drinks-price: 2000
humans-price: 2000
humanoid-price: 2000
miscellaneous-price: 2000
monsters-price: 2000
plants-price: 2000
custom-price: 100000
custom2-price: 250000
custom3-price: 500000
custom4-price: 1000000
online_players-price: 50000

# you can set the category ID's here

alphabet-id: 164
animals-id: 335
blocks-id: 106
decoration-id: 4151
food_drinks-id: 22
humans-id: 3996
humanoid-id: 1530
miscellaneous-id: 537
monsters-id: 4187
plants-id: 4982
custom-id: 242
custom2-id: 242
custom3-id: 242
custom4-id: 242
online_players-id: 2669

# format= name: "base64"
# do not use any ,'s in your name !
# you can use uuid:[player-uuid] to use normal players their skins
# tutorial: https://www.youtube.com/watch?v=upc4gOAQN5Y
custom:
  isaac_kern: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvY2UyMTRlOWVkYTk4MTY1ZDhkZjM0YjhkMGE1MWM3YzE0NGNhYTc4MzU4MzQ3NDM4YmYzMzMyMWYxMjliNyJ9fX0="
  MrOmegaBeast: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWIxN2UyOTUyNGZjNzg1YjE5MmFiN2FiMWNlYjllNzU1ZGUzN2U2YjJmMzY4NDU0NDYzZjA3M2Y2MGUxODIifX19"
custom2:
  Dustehhh: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDkyMmRmMTcyZmQ1MjViOTk1NzNmODYxNDE0ZDZlMTcxN2YxNzMzOTY3NjE3YmUzYzQ4M2VlNzMyZmE4N2M3In19fQ=="
  o7_Frost: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2ZhOTU1N2MyMDUwOTZlY2FkNmMxYzExN2RkY2U2ZTE4YWQ2NDJkNmM1NzlmNzc1ZjkwN2ZmZjlkNjI4ODUwIn19fQ=="
  Katsuki_Black: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjc5OGViNmZmNzg4MTg3ZWNlYTZlOTY4NmQ3NjJlNzk3NzVlMTdiOTk1ZGUyYTdjNDE2MjEzMTgwZjE3YSJ9fX0="
  Zdok: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYmFkZjc2OGEyNTgwMTJhZDg4MWFkOWJiMWY4ZTUxNGZmNDM0NmMxY2UyZjQ3N2E4NTEwMmU4ZTcyNDdhMyJ9fX0="
custom3:
  CavemanlyMan: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGJiOTVlZDE5MjJkYjVjYzM4YWU1NDI5NDMxZjBjNzc5NzIyYjc0NWRmNDNjMTNkNmUzMjJiZGQ1OWRjZCJ9fX0="
  SuperLinkNL: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWIzZTZmNmMyZjRjZDVjNDljMzA3OTdhYmExYzgxYmQxNGI0NWVkMTU1ZjdmMWRmYTRlNDUyYTZiZWYzMzkzNSJ9fX0="
custom4:
  _Syntax_Error: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWVhMGVlYjczYzEwNzI0YjdmZTAyZjM0ODI4ZWQ5ZmFiNTQxYzMxYWFhYjU1YzU0YWFkZTUyMGYxYTk1YTQyIn19fQ=="
  LadyKaviir: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjk2NGFmZTg0NDhlZWRmMzQ5YTgxMjcwOWI4Mzc4OTk3NDY1YzhjOTkzYWZjMGQ1YzlkOTI4ZjU2ZTIzYjY5ZiJ9fX0="
  
